### ISSUE TITLE
CIS-CAT rules

### ISSUE THREAD

**Issue by jirwin** [racker/mmi-base-cookbook#4]
This seems like a good place to take care the various CIS-CAT requirements for PCI compliance.
## TODO
- [ ] Write audit-mode or Serverspec tests for rules applicable to our target platforms.
- [ ] Write recipes to make those tests pass.
- [ ] OPTIONAL: Make base cloud images that pass the tests.

The audit-cis cookbook is a good place to start, but it only advertises official support for CentOS 6 & 7 now. It looks like work on Ubuntu 14.04 is in master though.
## References

https://benchmarks.cisecurity.org/downloads/audit-tools/
https://supermarket.chef.io/cookbooks/audit-cis
https://github.rackspace.com/GSS/Hardening-Ubuntu
